name: PyPI publish on release
on:
  release:
jobs:
  build-package:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Verify tag matches version
        run: |
          version = $(cat VERSION)
          tag = $GITHUB_REF
          if [[ "v$version" != "$tag" ]]; then
            exit 1
          fi
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: |
          python -m pip install -U pip setuptools twine
      - run: |
          python setup.py sdist
      - name: Setup PyPI config
        run: |
          cat << EOF > ~/.pypirc
          [distutils]
          index-servers = testpypi
          [testpypi]
          repository=https://test.pypi.org/legacy/
          username=__token__
          password=${{ secrets.PYPI_TOKEN }}
          EOF
      - run: |
          twine upload --repository testpypi dist/*.tar.gz
